### ISSUE TITLE
Add in error-handling for missing hostname

### ISSUE THREAD

**Issue by corvese** [corvese/cisco_switchport_auditor#1]
If a file is parsed that does not have a hostname in it according to Cisco's command syntax, an error will be returned and cause the program to crash. I experienced this by accidentally including a non-Cisco device's configuration in a directory referenced that also contain Cisco device configurations

Example of error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/myuser/Python/PROJECTS/cisco_switchport_auditor/cisco_switchport_auditor/master_functions.py", line 37, in parse_from_config_file
    ParserRunningConfigSwitch(switch, config)
  File "/home/myuser/Python/PROJECTS/cisco_switchport_auditor/cisco_switchport_auditor/parsers/parser_running_config_switch.py", line 26, in __init__
    self._parse_running_config_for_data()
  File "/home/myuser/Python/PROJECTS/cisco_switchport_auditor/cisco_switchport_auditor/parsers/parser_running_config_switch.py", line 59, in _parse_running_config_for_data
    self._switch.hostname = self._get_hostname()
  File "/home/myuser/Python/PROJECTS/cisco_switchport_auditor/cisco_switchport_auditor/parsers/parser_running_config_switch.py", line 70, in _get_hostname
    global_obj = self._parser.find_objects(r'^hostname')[0]
IndexError: list index out of range
```

**Comment by corvese** [comment]
Fixed in 5509fc0
